<?php
/**
 * TDMMoney
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @copyright   Gregory Mage (Aka Mage)
 * @license     GNU GPL 2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
 * @author      Gregory Mage (Aka Mage)
 */

$modversion['name']             = _MI_TDMMONEY_NAME;
$modversion['version']          = '1.1';
$modversion['description']      = _MI_TDMMONEY_DESC;
$modversion['credits']          = 'G. Mage';
$modversion['author']           = 'G. Mage';
$modversion['pseudo']           = 'Mage';
$modversion['website']          = 'www.freexoopservices.com';
$modversion['name_website']     = 'FreeXoopServices';
$modversion['license']          = 'GPL see LICENSE';
$modversion['official']         = 0;
$modversion['image']            = 'images/tdmmoney_logo.png';
$modversion['dirname']          = 'TDMMoney';
$modversion['status_version']   = 'Final';
$modversion['release_date']     = '2012/01/11';
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
$modversion['onUpdate']         = 'include/update.php';
$modversion['help']             = 'page=help';
$modversion['min_php']          = '5.2';
$modversion['min_xoops']        = '2.5';

// Admin menu
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Tables crée depuis le fichier sql
$modversion['tables'][0] = 'tdmmoney_account';
$modversion['tables'][1] = 'tdmmoney_category';
$modversion['tables'][2] = 'tdmmoney_operation';

// Pour avoir une administration
$modversion['hasAdmin'] =   1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] =  'admin/menu.php';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_TDMMONEY_SUBMIT;
$modversion['sub'][1]['url']  = 'submit.php';

// Recherche
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'TDMMoney_search';

// Templates
$modversion['templates'][1]['file'] = 'tdmmoney_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'tdmmoney_viewaccount.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'tdmmoney_submit.html';
$modversion['templates'][3]['description'] = '';

// Préférences
$i = 1;
include_once XOOPS_ROOT_PATH . '/class/xoopslists.php';
$modversion['config'][$i]['name']           = 'TDMMoney_editor';
$modversion['config'][$i]['title']          = '_MI_TDMMONEY_EDITOR';
$modversion['config'][$i]['description']    = '';
$modversion['config'][$i]['formtype']       = 'select';
$modversion['config'][$i]['valuetype']      = 'text';
$modversion['config'][$i]['default']        = 'dhtmltextarea';
$modversion['config'][$i]['options']        = XoopsLists::getDirListAsArray(XOOPS_ROOT_PATH . '/class/xoopseditor');
$modversion['config'][$i]['category']       = 'global';
$i++;
$modversion['config'][$i]['name']           = 'TDMMoney_filter';
$modversion['config'][$i]['title']          = '_MI_TDMMONEY_FILTER';
$modversion['config'][$i]['description']    = '';
$modversion['config'][$i]['formtype']       = 'select';
$modversion['config'][$i]['valuetype']      = 'int';
$modversion['config'][$i]['default']        = 3;
$modversion['config'][$i]['options']        = array('_MI_TDMMONEY_FILTER1' => 1, '_MI_TDMMONEY_FILTER2' => 2, '_MI_TDMMONEY_FILTER3' => 3);
$i++;
?>